name: Customization Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint Bash & Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Makefile linter
        run: |
          make install-linters
          make lint
